<?php
			$optionsArray = array( 'welcome' => array( 'welcomeItems' => array( 'collapse_button' => array( 'menutItem' => false ),
'loginform_login' => array( 'menutItem' => false ),
'username_button' => array( 'menutItem' => false ),
'logo' => array( 'menutItem' => false ),
'expand_button' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'image' => array( 'menutItem' => false ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'users',
'page' => 'list' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'branch',
'page' => 'list' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'payroll',
'page' => 'list' ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'employee',
'page' => 'list' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'task assign',
'page' => 'list' ),
'welcome_item4' => array( 'menutItem' => true,
'group' => false,
'items' => null,
'table' => 'notice',
'page' => 'list' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'above-grid' => array( 'image' ),
'grid' => array( 'welcome_item1',
'welcome_item3',
'welcome_item5',
'welcome_item',
'welcome_item2',
'welcome_item4' ) ),
'formXtTags' => array(  ),
'itemForms' => array( 'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'image' => 'above-grid',
'welcome_item1' => 'grid',
'welcome_item3' => 'grid',
'welcome_item5' => 'grid',
'welcome_item' => 'grid',
'welcome_item2' => 'grid',
'welcome_item4' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'collapse_button' => 5,
'loginform_login' => 3,
'username_button' => 3,
'expand_button' => 5,
'menu' => 3 ) ),
'itemsByType' => array( 'image' => array( 'image' ),
'logout_link' => array( 'logout_link' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'collapse_button' => array( 'collapse_button' ),
'welcome_item' => array( 'welcome_item',
'welcome_item1',
'welcome_item2',
'welcome_item3',
'welcome_item4',
'welcome_item5' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'menu-topbar',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'image' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'welcome_item1',
'welcome_item3',
'welcome_item5' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'welcome_item',
'welcome_item2',
'welcome_item4' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'image' => array( 'type' => 'image',
'imagePath' => 'appwizard.png' ),
'logout_link' => array( 'type' => 'logout_link' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'welcome_item' => array( 'type' => 'welcome_item',
'linkTable' => 'employee',
'linkPage' => 'list',
'linkText' => array( 'table' => 'employee',
'type' => 6 ) ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkTable' => 'users',
'linkPage' => 'list',
'linkText' => array( 'table' => 'users',
'type' => 6 ) ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkTable' => 'task assign',
'linkPage' => 'list',
'linkText' => array( 'table' => 'task assign',
'type' => 6 ) ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkTable' => 'branch',
'linkPage' => 'list',
'linkText' => array( 'table' => 'branch',
'type' => 6 ) ),
'welcome_item4' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'notice',
'linkPage' => 'list',
'linkText' => array( 'table' => 'notice',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'fire' ),
'linkComments' => array( 'text' => '',
'type' => 0 ),
'background' => '#E8926F' ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'payroll',
'linkPage' => 'list',
'linkText' => array( 'table' => 'payroll',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'calendar' ),
'background' => '#E67349' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>